[versions]
androidGradlePlugin = "8.9.2"
androidJunit5 = "1.12.0.0"
androidsvg = "1.4"
androidTest = "1.7.0"
appcompat = "1.7.0"
assertJ = "3.27.3"
colorpicker = "1.1.5"
constraintlayout = "2.2.1"
desugar_jdk_libs = "2.1.5"
documentfile = "1.0.1"
junitJupiter = "5.12.2"
kotlin = "2.1.20"
lifecycleViewmodelKtx = "2.8.7"
mapsforge = "0.25.0"
material = "1.12.0"
mockk = "1.14.2"
preferenceKtx = "1.2.1"
runner = "1.6.2"
slf4jApi = "2.0.17"
jsoup = "1.20.1"
activity = "1.10.1"

[libraries]
android-test-runner = { module = "de.mannodermaus.junit5:android-test-runner", version.ref = "androidTest" }
android-test-core = { module = "de.mannodermaus.junit5:android-test-core", version.ref = "androidTest" }
androidsvg = { module = "com.caverock:androidsvg", version.ref = "androidsvg" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertJ" }
colorpicker = { module = "com.github.7Koston:HSVColorPicker", version.ref = "colorpicker" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
jsoup-jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitJupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junitJupiter" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
material = { module = "com.google.android.material:material", version.ref = "material" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
runner = { module = "androidx.test:runner", version.ref = "runner" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4jApi" }
vtm = { module = "org.mapsforge:vtm", version.ref = "mapsforge" }
vtm-android = { module = "org.mapsforge:vtm-android", version.ref = "mapsforge" }
vtm-http = { module = "org.mapsforge:vtm-http", version.ref = "mapsforge" }
vtm-themes = { module = "org.mapsforge:vtm-themes", version.ref = "mapsforge" }
activity = { module = "androidx.activity:activity", version.ref = "activity" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-junit5 = { id = "de.mannodermaus.android-junit5", version.ref = "androidJunit5" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }